name: Crosscompile

on:
  push:
    branches:
    - master

jobs:
  test:
    name: Run ./test_crosscompile.sh
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.17.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
        check-latest: true
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run ./test_crosscompile.sh
      run: ./test_crosscompile.sh