name: Crosscompile

on:
  push:
    branches:
    - master

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Generate matrix
        id: set-matrix
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json --names)"

    outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}

  test:
    name: "Build with  ${{ matrix.go_version }} for ${{ matrix.goos }}/${{ matrix.goarch }}"
    runs-on: ubuntu-latest
    needs: generate_matrix

    strategy:
        matrix: ${{ fromJson(needs.generate_matrix.outputs.matrix) }}

    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
        check-latest: true
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build
      run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 GOFLAGS='-v -ldflags=-s -ldflags=-w' go build -v