name: Build and test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.17.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
        check-latest: true
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Lint
      run: golangci-lint run -c .golangci.yml


  crosscompile:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.17.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
        check-latest: true
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run test_crosscompile
      run: ./test_crosscompile.sh

  test:

    runs-on: ${{ matrix.platform }}
    name: "build (${{ matrix.platform }})"

    strategy:
        matrix:
          platform:
            - macos-latest
            - ubuntu-latest
            - windows-latest

    steps:
    - name: Set up Go 1.17.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
        check-latest: true
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build
      run: go build
    - name: Test
      run: go test