name: Build and test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    name: "Test (${{ matrix.platform }})"

    strategy:
        matrix:
          platform:
            - ubuntu-latest
            - macos-latest

    steps:
    - name: Set up Go 1.17.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
        check-latest: true
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build
      run: go build -v
    - name: Test
      run: go test -v