name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    name: "Test go ${{ matrix.go_version }} on ${{ matrix.platform }}"

    strategy:
        matrix:
          platform:
            - ubuntu-latest
            - macos-latest
          go_version:
            - 1.13.x
            - 1.17.x
            - 1.18.x

    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
        check-latest: true
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build
      run: go build -v
    - name: Test
      run: go test -v